### ISSUE TITLE
Missing Metadata in expanded Entitites

### ISSUE THREAD

**Issue by dirk-ecker** [FraunhoferIOSB/FROST-Server#1023]
When I request a Thing via GET with all Datastreams 

`
server:port/FROST-Server/v1.1/Things?$filter=name eq '<name>'&$expand=Datastreams
`

I would expect that I also get the links to the Sensor of each Datastream as in 

`
server:port/FROST-Server/v1.1/Things(14)/Datastreams
`
but this is not the case.

Is this as designed, means expanded Entities never contains their nested Entities?

**Comment by hylkevds** [comment]
This is by design. To reduce the size of the resulting document, only top-level entities get all navigation links.

**Comment by dirk-ecker** [comment]
But it is possible. This gives me the Sensor.

`
https://ogc-demo.k8s.ilt-dmz.iosb.fraunhofer.de/FROST-SoilThings/v1.1/Things?$filter=name eq 'SoilHorizon_soilhorizon.2019-007748'&$expand=Datastreams($select=Sensor)
`

So the reason why this is not possible with our FROST Server Instance has to do with?

We use the actual release. Do we have to configure this?

**Comment by hylkevds** [comment]
Explicitly requesting the navigationLinks should work on any FROST-Server.
Can you check in the logs which version of FROST you are using?

**Comment by dirk-ecker** [comment]
It seems to be version 1.15.0.

The result is simply empty.

In the logs I can see this

```
2022-07-04 14:00:11,854 353827857 [http-nio-8080-exec-6] ERROR d.f.i.i.f.f.ResultFormatterDefault - Failed to format response.
com.fasterxml.jackson.databind.JsonMappingException: Current context not Object but Array (through reference chain: de.fraunhofer.iosb.ilt.frostserver.model.core.EntitySetImpl[0])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:392)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:363)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:338)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:153)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:107)
	at com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:25)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3160)
	at com.fasterxml.jackson.core.base.GeneratorBase.writeObject(GeneratorBase.java:389)
	at de.fraunhofer.iosb.ilt.frostserver.json.serialize.EntitySetResultSerializer.serialize(EntitySetResultSerializer.java:47)
	at de.fraunhofer.iosb.ilt.frostserver.json.serialize.EntitySetResultSerializer.serialize(EntitySetResultSerializer.java:32)

```

**Comment by dirk-ecker** [comment]
Seems to be more than one Sensor?

**Comment by dirk-ecker** [comment]
Oh I found it, sorry for the request.
We replaced the table with a view and so it is our fault, that there is more than one sensor found.
