### ISSUE TITLE
Failed to initialise Catalina CORS filter with Tomcat 9.0.31

### ISSUE THREAD

**Issue by qwertZ1984** [FraunhoferIOSB/FROST-Server#1314]
Hello, 

i have an issue with CORS.
My ERROR :  
Failed to initialise Catalina CORS filter:

```
2022-12-02 21:10:37,806 979  [main] INFO  d.f.i.i.f.settings.Settings - Setting http.cors.enable has value 'true'.
2022-12-02 21:10:37,808 981  [main] ERROR d.f.i.i.f.h.c.AbstractContextListener - Failed to initialise Catalina CORS filter.
java.lang.NullPointerException: null
        at de.fraunhofer.iosb.ilt.frostserver.http.common.AbstractContextListener.setUpCatalinaCorsFilter(AbstractContextListener.java:145)
        at de.fraunhofer.iosb.ilt.frostserver.http.common.AbstractContextListener.setUpCorsFilter(AbstractContextListener.java:127)
        at de.fraunhofer.iosb.ilt.frostserver.http.common.AbstractContextListener.contextInitialized(AbstractContextListener.java:92)
        at de.fraunhofer.iosb.ilt.frostserver.ContextListener.contextInitialized(ContextListener.java:40)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4685)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5146)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
        at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1132)
        at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:1866)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
        at org.apache.catalina.startup.HostConfig.deployDirectories(HostConfig.java:1044)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:429)
        at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1575)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
        at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:633)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:343)
```

Tomcat loads the Filter. There is no Error in logfile:

```
02-Dec-2022 21:10:38.057 FINE [main] org.apache.catalina.core.StandardContext.filterStart Starting filters
02-Dec-2022 21:10:38.057 FINE [main] org.apache.catalina.core.StandardContext.filterStart  Starting filter 'CorsFilter'
02-Dec-2022 21:10:38.059 FINE [main] org.apache.catalina.core.StandardContext.filterStart  Starting filter 'Tomcat WebSocket (JSR356) Filter'
02-Dec-2022 21:10:38.059 FINE [main] org.apache.catalina.core.StandardContext.filterStart  Starting filter 'AuthFilterSta'
```

Have you any Idea?

Best Regards

**Comment by hylkevds** [comment]
That normally only happens when there already is a Filter with the name `CorsFilter` in the ServletContext that FROST runs in. Did you manually add a Cors filter in your Web.xml or Server.xml ?

**Comment by qwertZ1984** [comment]
I need to add PATCH and DELETE to FROST. Because  I get 403 ERROR.
SensorThingsServcie.log says:
```
2022-12-05 08:31:18,899 1022 [main] INFO  d.f.i.i.f.settings.Settings - Setting http.cors.enable has value 'true'.
2022-12-05 08:31:18,903 1026 [main] INFO  d.f.i.i.f.settings.Settings - Not set http.cors.allowed.origins, using default value '*'.
2022-12-05 08:31:18,903 1026 [main] INFO  d.f.i.i.f.settings.Settings - Not set http.cors.allowed.methods, using default value 'GET,POST,HEAD,OPTIONS'.
```
So did manually add a Cors filter  in tomcat_conf/web.xml and i also tried in webapps/FROST-Server/WEB-INF/web.xml
as desribed in  webapps/FROST-Server/WEB-INF/web.xml.

**Comment by hylkevds** [comment]
If you manually add a CORS filter you can't use the FROST one. But you can configure all settings in the FROST one, so you don't need to use a manual one. The settings to use are even directly in the log file! But you can also find them in the documentation.

**Comment by qwertZ1984** [comment]
Thank you. It was my fault.
Didn't read the documentation correctly.
Now it works.
