### ISSUE TITLE
MQTT Endpoint: difference between local bus and external bus?

### ISSUE THREAD

**Issue by rduivenvoorde** [FraunhoferIOSB/FROST-Server#1384]
Running a local 'All in One' HTTP/MQTT server with docker compose (like described in docs), I can create a sensor like this:

```
mosquitto_pub -i 'mosquitto_Pub-richard' -h localhost -t "v1.1/Sensors" -m' {
  "name": "Saphymo Gammadetector",
  "description": "Saphymo Gammadetector description",
  "encodingType": "application/pdf",
  "metadata": "https://rivm.nl/datasheets/Saphymo.pdf"
}'
```
this will show up in the HTTP list of Sensors.

Now we try to setup Frost in Kubernetes, with one MQTT and one HTTP module, listening to an existing simple Mosquitto MQTT broker (also in Kubernetes), the so called "Separated HTTP & MQTT packages"-setup.

Frost-MQTT is started (in kubernetes) with the following parameters: 
```
│       FROST_LL:                                           DEBUG                                                                                                                                           │
│       ApiVersion:                                         v1.1                                                                                                                                            │
│       serviceRootUrl:                                     https://frost.kuubdev.cal-net.nl                                                                                                                │
│       enableActuation:                                    false                                                                                                                                           │
│       defaultCount:                                       false                                                                                                                                           │
│       defaultTop:                                         100                                                                                                                                             │
│       maxTop:                                             1000                                                                                                                                            │
│       maxDataSize:                                        25000000                                                                                                                                        │
│       useAbsoluteNavigationLinks:                         true                                                                                                                                            │
│       mqtt_mqttServerImplementationClass:                 de.fraunhofer.iosb.ilt.sensorthingsserver.mqtt.moquette.MoquetteMqttServer                                                                      │
│       mqtt_Enabled:                                       true                                                                                                                                            │
│       mqtt_Port:                                          1883                                                                                                                                            │
│       mqtt_Host:                                          0.0.0.0                                                                                                                                         │
│       mqtt_internalHost:                                  localhost                                                                                                                                       │
│       mqtt_WebsocketPort:                                 9876                                                                                                                                            │
│       mqtt_WaitForEnter:                                  false                                                                                                                                           │
│       mqtt_QoS:                                           2                                                                                                                                               │
│       mqtt_SubscribeMessageQueueSize:                     100                                                                                                                                             │
│       mqtt_SubscribeThreadPoolSize:                       10                                                                                                                                              │
│       mqtt_CreateMessageQueueSize:                        100                                                                                                                                             │
│       mqtt_CreateThreadPoolSize:                          10                                                                                                                                              │
│       mqtt_maxInFlight:                                   50                                                                                                                                              │
│       bus_mqttBroker:                                     tcp://mqtt-svc.mqtt.svc.cluster.local:1883                                                                                                      │
│       bus_busImplementationClass:                         de.fraunhofer.iosb.ilt.sta.messagebus.MqttMessageBus                                                                                            │
│       bus_topicName:                                      FROST-Bus                                                                                                                                       │
│       bus_qosLevel:                                       2                                                                                                                                               │
│       bus_sendWorkerPoolSize:                             10                                                                                                                                              │
│       bus_sendQueueSize:                                  100                                                                                                                                             │
│       bus_recvWorkerPoolSize:                             10                                                                                                                                              │
│       bus_recvQueueSize:                                  100                                                                                                                                             │
│       bus_maxInFlight:                                    50  
```

Though we see Frost MQTT listen/react to our central bus, I fail to find the right topic to construct the same sensor.

Tried `FROST-Bus`, `FROST-Bus/v1.1` `FROST-Bus/v1.1/Sensors` but it looks like Frost ONLY listens to `FROST-Bus`...
BUT then throws the following message in logs:

```
│ 13:38:28.562 [MQTT Call: FROST-MQTT-Bus-ae582e97-11ba-4d51-a066-73752fcc5a43] WARN  d.f.i.i.f.j.d.c.CustomEntityChangedMessageDeserializer - Unknown field in message: name                             │
│ 13:38:28.562 [MQTT Call: FROST-MQTT-Bus-ae582e97-11ba-4d51-a066-73752fcc5a43] WARN  d.f.i.i.f.j.d.c.CustomEntityChangedMessageDeserializer - Unknown field in message: description                      │
│ 13:38:28.563 [MQTT Call: FROST-MQTT-Bus-ae582e97-11ba-4d51-a066-73752fcc5a43] WARN  d.f.i.i.f.j.d.c.CustomEntityChangedMessageDeserializer - Unknown field in message: encodingType                     │
│ 13:38:28.563 [MQTT Call: FROST-MQTT-Bus-ae582e97-11ba-4d51-a066-73752fcc5a43] WARN  d.f.i.i.f.j.d.c.CustomEntityChangedMessageDeserializer - Unknown field in message: metadata                         │
│ 13:38:28.563 [MQTT Call: FROST-MQTT-Bus-ae582e97-11ba-4d51-a066-73752fcc5a43] ERROR     d.f.i.i.f.m.MqttMessageBus - Failed to decode message from bus. Details in DEBUG.                               │
│ 13:38:28.563 [MQTT Call: FROST-MQTT-Bus-ae582e97-11ba-4d51-a066-73752fcc5a43] DEBUG     d.f.i.i.f.m.MqttMessageBus - Failed to decode message: {                                                        │
│   "name": "Saphymo Gammadetector",                                                                                                                                                                      │
│   "description": "Saphymo Gammadetector description",                                                                                                                                                   │
│   "encodingType": "application/pdf",                                                                                                                                                                    │
│   "metadata": "https://rivm.nl/datasheets/Saphymo.pdf"                                                                                                                                                  │
│ }                                                                                                                                                                                                       │
│ java.lang.IllegalArgumentException: Message json with no type or no entity.                                                                                                                             │
│     at de.fraunhofer.iosb.ilt.frostserver.json.deserialize.custom.CustomEntityChangedMessageDeserializer.deserialize(CustomEntityChangedMessageDeserializer.java:91)                                    │
│     at de.fraunhofer.iosb.ilt.frostserver.json.deserialize.custom.CustomEntityChangedMessageDeserializer.deserialize(CustomEntityChangedMessageDeserializer.java:38) 
```

So it looks like that it does not find/use the topic to determine the type to parse?

It's also not clear to me what the `mqtt_mqttServerImplementationClass` property is doing.

Anybody an example of MQTT-publish working in a "Separated HTTP & MQTT packages"-setup ?

**Comment by hylkevds** [comment]
The MessageBus is only for internal communication between FROST components. It's what a FROST-HTTP component uses to tell the FROST-MQTT components that (for instance) a new Observation was inserted. End users should never be able to connect to this message bus. This is why in the [docker-compose-separated.yaml](https://github.com/FraunhoferIOSB/FROST-Server/blob/v2.x/scripts/docker-compose-separated.yaml) example the mosquitto message bus has no external ports defined.

The FROST-MQTT component is the MQTT broker that end users connect to. As per the standard, users use the topics `v1.1/EntityType`, like `v1.1/Things`, `v1.1/Observations`, `v1.1/Datastreams(1)/Observations`

The `mqtt_mqttServerImplementationClass` is the specific implementation used internally in the FROST-MQTT component. This is like the `persistenceManagerImplementationClass`. Currently there is only one implementation.

**Comment by rduivenvoorde** [comment]
Ok, sorry for the confusion. From this image:

![image](https://user-images.githubusercontent.com/731673/212947679-143cf55c-1282-4157-8327-fa92f8f36da0.png)

we were under the (wrong) impression that the FROST-MQTT (and HTTP) components could act as a MQTT-CLIENT, subscribing/publishing to a generic central bus.

So when I ran the docker-compose-separated.yaml containers I was (again wrong in) thinking that I was publishing my Sensor/Datastream etc to this generic central bus (not knowing that I was actually publishing to the FROST-MQTT component directly).

So the model is that Frost-Server itself is acting as a Broker/endpoint and the BUS in the image is internal communication...
In our case the sensor measurements are placed on a central MQTT bus, so then we will probably configure that bus to bridge messages (both ways) to/from FROST-MQTT (endpoint in kubernetes)...

The creation of Entities, IS a valid usecase of FROST-MQTT isn't it?

**Comment by hylkevds** [comment]
The FROST-MQTT and -HTTP components _are_ MQTT-clients for the message bus, but end-users are not. This is also why the smily faces have arrows to/from the FROST-Components, and the FROST-Components have arrows to the BUS and Database.

Creation of Observations is Standard SensorThings, Creation of other entities is not, but FROST still allows it (no reason not to).
