### ISSUE TITLE
Server Error 500 when trying to patch a thing

### ISSUE THREAD

**Issue by mikedolx** [FraunhoferIOSB/FROST-Server#1688]
Hi,

i'm currenlty trying to patch a property of a thing using the python client. Unfortunately, i'm getting an HTTP error when trying to do so (which is why i'm posting the issue in this repo).

I'm using this code snippet for the update attempt:
```python
thing = things.entities[0]
logging.debug(f'found thing {thing.name}')
# update the thing
patches = []
if 'status' in thing.properties:
    # remove the status property, when it's existing
    patches.append({'op': 'remove', 'path': '/properties/status'})

patches.append(
    {'op': 'add', 'path': '/properties/status', 'value': status})

service.patch(thing, patches=JsonPatch(patch=patches))
```

The error, when i execute the last line in python:

```python
Exception has occurred: HTTPError
500 Server Error:  for url: https://frost-dev.mydomain.com:8443/FROST-Server/v1.1/Things(28)
  File "push-rudis-status2frost.py", line 46, in <module>
    service.patch(thing, patches=JsonPatch(patch=patches))
requests.exceptions.HTTPError: 500 Server Error:  for url: https://frost-dev.mydomain.com:8443/FROST-Server/v1.1/Things(28)
```

When i take a look into the server, i can see the following exception beeing raised by the server. Unfortunately, i have no clue, what it could mean. Do you have any idea? Is this a bug in the server?

```java
frost-web-mqtt | 15:38:38.166 [http-nio-8080-exec-2] DEBUG    d.f.i.i.f.p.path.PathParser - Parsing: /Things(28)
frost-web-mqtt | 15:38:38.171 [http-nio-8080-exec-2] ERROR      d.f.i.i.f.service.Service - Failed to handle request (details in debug): Cannot invoke "java.util.Set.isEmpty()" because the return value of "de.fraunhofer.iosb.ilt.frostserver.model.EntityChangedMessage.getEpFields()" is null
frost-web-mqtt | 15:38:38.171 [http-nio-8080-exec-2] DEBUG      d.f.i.i.f.service.Service - Exception:
frost-web-mqtt | java.lang.NullPointerException: Cannot invoke "java.util.Set.isEmpty()" because the return value of "de.fraunhofer.iosb.ilt.frostserver.model.EntityChangedMessage.getEpFields()" is null
frost-web-mqtt |        at de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq.PostgresPersistenceManager.doUpdate(PostgresPersistenceManager.java:348)
frost-web-mqtt |        at de.fraunhofer.iosb.ilt.frostserver.persistence.AbstractPersistenceManager.update(AbstractPersistenceManager.java:142)
frost-web-mqtt |        at de.fraunhofer.iosb.ilt.frostserver.service.Service.handleChangeSet(Service.java:608)
frost-web-mqtt |        at de.fraunhofer.iosb.ilt.frostserver.service.Service.executePatch(Service.java:538)
frost-web-mqtt |        at de.fraunhofer.iosb.ilt.frostserver.service.Service.execute(Service.java:175)
frost-web-mqtt |        at de.fraunhofer.iosb.ilt.frostserver.plugin.coremodel.PluginCoreService.execute(PluginCoreService.java:139)
frost-web-mqtt |        at de.fraunhofer.iosb.ilt.frostserver.http.common.ServletMain.executeService(ServletMain.java:113)
frost-web-mqtt |        at de.fraunhofer.iosb.ilt.frostserver.http.common.ServletMain.processRequest(ServletMain.java:95)
frost-web-mqtt |        at de.fraunhofer.iosb.ilt.frostserver.http.common.ServletMain.doPatch(ServletMain.java:149)
frost-web-mqtt |        at de.fraunhofer.iosb.ilt.frostserver.http.common.ServletMain.service(ServletMain.java:170)
frost-web-mqtt |        at javax.servlet.http.HttpServlet.service(HttpServlet.java:596)
frost-web-mqtt |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:209)
frost-web-mqtt |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
frost-web-mqtt |        at de.fraunhofer.iosb.ilt.frostserver.auth.basic.BasicAuthFilter.doFilter(BasicAuthFilter.java:182)
frost-web-mqtt |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
frost-web-mqtt |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
frost-web-mqtt |        at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:328)
frost-web-mqtt |        at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:158)
frost-web-mqtt |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
frost-web-mqtt |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
frost-web-mqtt |        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
frost-web-mqtt |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
frost-web-mqtt |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
frost-web-mqtt |        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167)
frost-web-mqtt |        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
frost-web-mqtt |        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492)
frost-web-mqtt |        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
frost-web-mqtt |        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
frost-web-mqtt |        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:673)
frost-web-mqtt |        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
frost-web-mqtt |        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
frost-web-mqtt |        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
frost-web-mqtt |        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
frost-web-mqtt |        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
frost-web-mqtt |        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
frost-web-mqtt |        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
frost-web-mqtt |        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
frost-web-mqtt |        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
frost-web-mqtt |        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
frost-web-mqtt |        at java.base/java.lang.Thread.run(Thread.java:833)
```

This is the json representation of the thing i'm trying to update.

```json
{
	"@iot.selfLink": "https://frost-dev.mydomain.com:8443/FROST-Server/v1.1/Things(28)",
	"@iot.id": 28,
	"name": "Sensor",
	"description": "",
	"properties": {
		"status": "decomissioned"
	},
	"Locations@iot.navigationLink": "https://frost-dev.mydomain.com:8443/FROST-Server/v1.1/Things(28)/Locations",
	"HistoricalLocations@iot.navigationLink": "https://frost-dev.mydomain.com:8443/FROST-Server/v1.1/Things(28)/HistoricalLocations",
	"Datastreams@iot.navigationLink": "https://frost-dev.mydomain.com:8443/FROST-Server/v1.1/Things(28)/Datastreams"
},
```

**Comment by hylkevds** [comment]
Which version of FROST-Server are you using?

**Comment by mikedolx** [comment]
Hi,
i just realized, that we have been using a custom made docker container. Allthough it was based on a development version of 2.2.0, after switching to the official 2.2.0-SNAPSHOT image, the problem was solved.
