### ISSUE TITLE
ClassNotFoundException org.postgresql.core.Provider when deploying WAR to Tomcat9

### ISSUE THREAD

**Issue by matcho** [FraunhoferIOSB/FROST-Server#282]
Hi.

Trying to deploy `FROST-Server.MQTTP-1.12.0.war` under Tomcat, I get the folloging error : `java.lang.ClassNotFoundException: org.postgresql.core.Provider` (stack trace below).

Installing JDBC PostgreSQL driver (`libpostgresql-jdbc-java`) and PostgreSQL server did not change anything.

Thank you for any help.

OS : Ubuntu 20.04
Tomcat : 9.0.31-1
Java : "14.0.2" 2020-07-14 (issue also occured with OpenJDK 11)
libpostgresql-jdbc-java : 42.2.10-1

```
08-Oct-2020 14:44:15.620 INFO [http-nio-8080-exec-2] org.apache.catalina.core.ApplicationContext.log HTMLManager: init: Global resources are available
08-Oct-2020 14:44:15.623 INFO [http-nio-8080-exec-2] org.apache.catalina.core.ApplicationContext.log HTMLManager: list: Listing contexts for virtual host 'localhost'
08-Oct-2020 14:44:24.873 INFO [http-nio-8080-exec-6] org.apache.catalina.core.ApplicationContext.log HTMLManager: start: Starting web application '/FROST-Server.MQTTP-1.12.0
'
08-Oct-2020 14:44:26.787 SEVERE [http-nio-8080-exec-6] org.apache.catalina.core.StandardContext.listenerStart Exception lors de l'envoi de l'évènement contexte initialisé (c
ontext initialized) à l'instance de classe d'écoute (listener) [de.fraunhofer.iosb.ilt.frostserver.ContextListener]
        java.lang.NoClassDefFoundError: org/postgresql/core/Provider
                at java.base/java.lang.ClassLoader.defineClass1(Native Method)
                at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
                at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:151)
                at org.apache.catalina.loader.WebappClassLoaderBase.findClassInternal(WebappClassLoaderBase.java:2419)
                at org.apache.catalina.loader.WebappClassLoaderBase.findClass(WebappClassLoaderBase.java:865)
                at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1334)
                at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1188)
                at de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq.PostgresPersistenceManager.init(PostgresPersistenceManager.java:86)
                at de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq.imp.PostgresPersistenceManagerLong.init(PostgresPersistenceManagerLong.java:66)
                at de.fraunhofer.iosb.ilt.frostserver.persistence.PersistenceManagerFactory.create(PersistenceManagerFactory.java:108)
                at de.fraunhofer.iosb.ilt.frostserver.persistence.PersistenceManagerFactory.getIdManager(PersistenceManagerFactory.java:124)
                at de.fraunhofer.iosb.ilt.frostserver.mqtt.subscription.SubscriptionFactory.<init>(SubscriptionFactory.java:82)
                at de.fraunhofer.iosb.ilt.frostserver.mqtt.subscription.SubscriptionFactory.init(SubscriptionFactory.java:53)
                at de.fraunhofer.iosb.ilt.frostserver.mqtt.MqttManager.init(MqttManager.java:108)
                at de.fraunhofer.iosb.ilt.frostserver.mqtt.MqttManager.<init>(MqttManager.java:103)
                at de.fraunhofer.iosb.ilt.frostserver.mqtt.MqttManager.init(MqttManager.java:78)
                at de.fraunhofer.iosb.ilt.frostserver.ContextListener.contextInitialized(ContextListener.java:37)
                at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4685)
                at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5146)
                at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
                at org.apache.catalina.manager.ManagerServlet.start(ManagerServlet.java:1415)
                at org.apache.catalina.manager.HTMLManagerServlet.start(HTMLManagerServlet.java:700)
                at org.apache.catalina.manager.HTMLManagerServlet.doPost(HTMLManagerServlet.java:223)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.catalina.filters.CsrfPreventionFilter.doFilter(CsrfPreventionFilter.java:211)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.catalina.filters.CsrfPreventionFilter.doFilter(CsrfPreventionFilter.java:211)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:666)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
                at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.base/java.lang.Thread.run(Thread.java:832)
        Caused by: java.lang.ClassNotFoundException: org.postgresql.core.Provider
                at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1365)
                at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1188)
                ... 50 more

**Comment by hylkevds** [comment]
It's mentioned in the [docs](https://fraunhoferiosb.github.io/FROST-Server/deployment/postgresql.html), though I should probably rename that page to "Tomcat Deployment":
You have to copy the [Postgres JDBC jar](https://repo.maven.apache.org/maven2/org/postgresql/postgresql/42.2.16/postgresql-42.2.16.jar) and the [postgis jar](https://repo.maven.apache.org/maven2/net/postgis/postgis-jdbc/2.4.0/postgis-jdbc-2.4.0.jar) to $CATALINA_HOME/lib.

**Comment by matcho** [comment]
Thank you so much !

My apologies for not entirely reading the docs.

**Comment by hylkevds** [comment]
No problem. I split the Tomcat doc bit into its own page now.
