### ISSUE TITLE
PostgreSQL database initialization with Tomcat 9

### ISSUE THREAD

**Issue by matcho** [FraunhoferIOSB/FROST-Server#283]
Hi again,

I swear I have read the documentation this time :)

Whatever I tried for database configuration leads to the same issue : `/DatabaseStatus` page says the following
```
de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq.imp.PostgresPersistenceManagerLong

Failed to initialise database:
Cannot create PoolableConnectionFactory (La tentative de connexion a échoué.)
```

"Database initialisation or upgrade" chapter tells to set `persistence.persistenceManagerImplementationClass` value, but does not specify in which file. I guess it's `webapps/FROST-Server.MQTTP-1.12.0/WEB-INF/web.xml`, but this parameter can also be found in `webapps/FROST-Server.MQTTP-1.12.0/META-INF/context.xml`. Do I have to edit both ?

Also, the default value and the recommanded values in the comments of both these 2 files mention different class names, starting with `de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq` and not `de.fraunhofer.iosb.ilt.sta.persistence.postgres`. Despite the changes listed below and the server restart / app reload, the error given by `DatabaseStatus` page mentions "*pgjooq" and not the class names that are defined in the config files.

Here's an excerpt of my `webapps/FROST-Server.MQTTP-1.12.0/WEB-INF/web.xml`
```xml
<context-param>
        <description>The java class used for persistence (must implement PersistenceManaher interface)</description>
        <param-name>persistence.persistenceManagerImplementationClass</param-name>
        <param-value>de.fraunhofer.iosb.ilt.sta.persistence.postgres.longid.PostgresPersistenceManagerLong</param-value>
        <!--<param-value>de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq.imp.PostgresPersistenceManagerLong</param-value>-->
        <!-- All options:
            de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq.imp.PostgresPersistenceManagerLong
            de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq.imp.PostgresPersistenceManagerString
            de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq.imp.PostgresPersistenceManagerUuid
        -->
    </context-param>
```

And here's an excert of my `webapps/FROST-Server.MQTTP-1.12.0/META-INF/context.xml`
```xml
<!-- persistence setting -->
    <Parameter override="false" name="persistence.persistenceManagerImplementationClass" value="de.fraunhofer.iosb.ilt.sta.persistence.postgres.longid.PostgresPersistenceManagerLong" description="The java class used for persistence (must implement PersistenceManaher interface)"/>
<!--<Parameter override="false" name="persistence.persistenceManagerImplementationClass" value="de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq.imp.PostgresPersistenceManagerLong" description="The java class used for persistence (must implement PersistenceManaher interface)"/>-->
    <!-- All options:
        de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq.imp.PostgresPersistenceManagerLong
        de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq.imp.PostgresPersistenceManagerString
        de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq.imp.PostgresPersistenceManagerUuid
    -->
```
I added a database resource into `$CATALINA_HOME/etc/server.xml` like this (probably not a good practice)
```xml
<Resource
            name="jdbc/sensorThings" auth="Container"
            type="javax.sql.DataSource" driverClassName="org.postgresql.Driver"
            url="jdbc:postgresql://localhost:5432/sensorthings"
            username="sensorthings" password="mypassword"
            maxTotal="20" maxIdle="10" maxWaitMillis="-1"/>
```

…although this resource seems to be already defined in `webapps/FROST-Server.MQTTP-1.12.0/META-INF/context.xml`. Do I have to make sure both are defined, or only one is needed ?

After adjusting those configuration files I restarted Tomcat and reloaded the FROST-Server app via Tomcat admin page, with no success.

Tomcat log says
```
2020-10-08 16:45:39,247 2204438 [http-nio-8080-exec-15] INFO  d.f.i.i.f.h.common.DatabaseStatus - DatabaseStatus Servlet called.
2020-10-08 16:45:39,296 2204487 [http-nio-8080-exec-15] ERROR d.f.i.i.f.p.p.PostgresPersistenceManager - Could not initialise database.
java.sql.SQLException: Cannot create PoolableConnectionFactory (La tentative de connexion a échoué.)
	at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:669)
	at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createDataSource(BasicDataSource.java:544)
	at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.getConnection(BasicDataSource.java:753)
	at de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq.ConnectionUtils$ConnectionSourceDataSource.getConnection(ConnectionUtils.java:192)
	at de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq.ConnectionUtils.getPoolingConnection(ConnectionUtils.java:96)
	at de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq.ConnectionUtils.getConnection(ConnectionUtils.java:77)
	at de.fraunhofer.iosb.ilt.frostserver.persistence.pgjooq.PostgresPersistenceManager.checkForUpgrades(PostgresPersistenceManager.java:326)
	at de.fraunhofer.iosb.ilt.frostserver.http.common.DatabaseStatus.checkForUpgrades(DatabaseStatus.java:127)
	at de.fraunhofer.iosb.ilt.frostserver.http.common.DatabaseStatus.processGetRequest(DatabaseStatus.java:80)
	at de.fraunhofer.iosb.ilt.frostserver.http.common.DatabaseStatus.doGet(DatabaseStatus.java:154)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: org.postgresql.util.PSQLException: La tentative de connexion a échoué.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:296)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:211)
	at org.postgresql.Driver.makeConnection(Driver.java:459)
	at org.postgresql.Driver.connect(Driver.java:261)
	at org.apache.tomcat.dbcp.dbcp2.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:55)
	at org.apache.tomcat.dbcp.dbcp2.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:355)
	at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.validateConnectionFactory(BasicDataSource.java:115)
	at org.apache.tomcat.dbcp.dbcp2.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:665)
	... 33 common frames omitted
Caused by: java.net.UnknownHostException: database
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at org.postgresql.core.PGStream.<init>(PGStream.java:81)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:92)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:196)
	... 41 common frames omitted
```

Note: "La tentative de connexion a échoué" is french for "Connection attempt failed".

Of course the PostgreSQL database is up and running, the login/password couple allows to successfully log in to `psql`, whether specifying `-h localhost` or not.

Thanks a lot for any help.
(and sorry for submitting the issue too quickly, I clicked the wrong button !)

**Comment by hylkevds** [comment]
Setting of options is listed on https://fraunhoferiosb.github.io/FROST-Server/settings/settings.html, but I've now also added it to the Tomcat/Wildfly sections since it makes sense there too.

The problem in your case is not the setting of `persistence.persistenceManagerImplementationClass`, since the default should work fine. The problem is the server tries to connect to the host named `database`, and this host does not exist. This is the default, used for the docker-compose deployment.

I think the `Resource` configuration in your `Server.xml` did not work... I think it should be in the `<Context>` that points to the War file...
Note that all configuration options are printed in the logs when they are used for the first time. That should help with debugging.

**Comment by matcho** [comment]
Thank you very much,

You're right, it turns out that a default database resource is already defined in `webapps/FROST-Server.MQTTP-1.12.0/META-INF/context.xml`, with a host set to `database:5432`.

For some reason the database resource defined in `server.xml` did not take precedence… which after all makes sense (context specific > general).

Unless it is a bad practice to edit this file once the .war is deployed, maybe the documentation could suggest to do so, instead of defining a new `<Resource…`  in Tomcat server-wide config ?

Everything works fine now, thank you.

**Comment by hylkevds** [comment]
It's odd the Server.xml resource doesn't take precedence. We're also deploying FROST on Tomcat, with that Resource defined in Server.xml.

Usually it's not a good idea to edit the context.xml from the war. It's better to edit the version that is copied to `$CATALINA_BASE/conf/[enginename]/[hostname]/appname.xml`. This copy is made automatically when copxXML is set to true.

**Comment by matcho** [comment]
OK. I'm new to Tomcat, so that's good to know, thank you.
