### ISSUE TITLE
authentication fails with correct username and password, resolve once docker container restarts

### ISSUE THREAD

**Issue by chenkianwee** [FraunhoferIOSB/FROST-Server#331]
I am facing this issue, where I have been posting to the FROST Server for days, suddenly authentication fails with the following message:
<!doctype html><html lang="en"><head><title>HTTP Status 401 – Unauthorized</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 401 – Unauthorized</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Description</b> The request has not been applied because it lacks valid authentication credentials for the target resource.</p><hr class="line" /><h3>Apache Tomcat/8.5.60</h3></body></html>

I did not change any of the authentication details. However, the problem is automatically resolve once I restart the docker container that is running the Frost server. What could be causing this? I am not sure how to debug this issue.

**Comment by hylkevds** [comment]
That's odd. Are there any messages on the console of the containers that have this issue?

**Comment by chenkianwee** [comment]
I checked the log. This is the error I am getting. It seems like the connection to the postgresql is closed? 

2021-01-07 02:33:59,543 714986786 [https-openssl-nio-8080-exec-6] ERROR d.f.i.i.f.a.basic.DatabaseHandler - Failed to check user rights.
org.jooq.exception.DataAccessException: SQL [select 1 as "one" from "USERS" left outer join "USER_ROLES" on "USERS"."USER_NAME" = "USER_ROLES"."USER_NAME" where ("USERS"."USER_NAME" = ? and "USERS"."USER_PASS" = ? and "USER_ROLES"."ROLE_NAME" = ?)]; This connection has been closed.
	at org.jooq_3.14.4.POSTGRES.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2904)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:757)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:389)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:481)
	at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:450)
	at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:464)
	at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:641)
	at org.jooq.impl.SelectImpl.fetchOne(SelectImpl.java:3074)
	at de.fraunhofer.iosb.ilt.frostserver.auth.basic.DatabaseHandler.userHasRole(DatabaseHandler.java:137)
	at de.fraunhofer.iosb.ilt.frostserver.auth.basic.BasicAuthFilter.requireRole(BasicAuthFilter.java:128)
	at de.fraunhofer.iosb.ilt.frostserver.auth.basic.BasicAuthFilter.lambda$init$2(BasicAuthFilter.java:103)
	at de.fraunhofer.iosb.ilt.frostserver.auth.basic.BasicAuthFilter.doFilter(BasicAuthFilter.java:159)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:364)
	at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:170)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:544)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:616)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:831)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1634)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.postgresql.util.PSQLException: This connection has been closed.
	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:885)
	at org.postgresql.jdbc.PgConnection.getAutoCommit(PgConnection.java:845)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:434)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:153)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:94)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.execute(DelegatingPreparedStatement.java:94)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:214)
	at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4192)
	at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:279)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:375)
	... 35 common frames omitted

**Comment by hylkevds** [comment]
Thanks for the stacktrace, I'll have a look at what may cause this.

**Comment by hylkevds** [comment]
The basic auth filter fetched a connection from the pool and held on to it indefinitely. This would make the filter fail if this connection ever closed. The filter now requests a connection from the pool every time, and closes it (returns it to the pool) afterwards. The pool will create new connections if one is closed for any reason.
