### ISSUE TITLE
Error messages in log: how to disable MQTT bus when using only HTTP module

### ISSUE THREAD

**Issue by matcho** [FraunhoferIOSB/FROST-Server#577]
Hello,

We've been succesfully using FrostServer (v1.14 then v2.0.0 dev) for a while now.

Although we're using only HTTP module, ie. deployed `FROST-Server.HTTP-*.war` into Tomcat, lots of INFO and ERROR messages related to MQTT are produced in the log, all looking like the following:

```
2021-09-23 13:08:38,648 420608 [pool-28-thread-1] INFO  d.f.i.i.f.messagebus.MqttMessageBus - paho-client connecting to broker: tcp://mosquitto:1883 with client-id FROST-MQTT-Bus-ca49d8a9-e2fd-436c-93d9-36bed9a54e87
2021-09-23 13:08:38,651 420611 [pool-28-thread-1] ERROR d.f.i.i.f.messagebus.MqttMessageBus - Failed to connect to broker: tcp://mosquitto:1883
2021-09-23 13:08:38,651 420611 [pool-28-thread-1] ERROR d.f.i.i.f.messagebus.MqttMessageBus - 
org.eclipse.paho.client.mqttv3.MqttException: MqttException
	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:738)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.net.UnknownHostException: mosquitto
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:333)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at org.eclipse.paho.client.mqttv3.internal.TCPNetworkModule.start(TCPNetworkModule.java:74)
	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:724)
	... 1 common frames omitted
```
Of course MQTT server is not reachable as none is deployed, on purpose.

Is it possible to disable MQTT bus when using only HTTP module ?

Tried setting `bus.busImplementationClass` and/or `bus.mqttBroker` to `''`, or even adding `mqtt.Enabled` set to `false`, with no success.

Thanks for any advice.

Greetings,
Mathias

**Comment by hylkevds** [comment]
You can use the internal message bus in that case
`bus.busImplementationClass=de.fraunhofer.iosb.ilt.sta.messagebus.InternalMessageBus`

**Comment by matcho** [comment]
Thank you very much ! It works.
