### ISSUE TITLE
AJAX Cross-origin Request

### ISSUE THREAD

**Issue by EOSIT** [FraunhoferIOSB/FROST-Server#75]
Please point me to the docs where it describes how to allow Javascript requests from different origins.

Thanks!

**Comment by hylkevds** [comment]
https://github.com/FraunhoferIOSB/FROST-Server/blob/master/docs/settings.adoc
Set `http.cors.enable` to true.

**Comment by EOSIT** [comment]
I now have the following environment settings in the YAML file, but still getting an error:

```
      - serviceRootUrl=http://test.dhcp:8081/FROST-Server
      - http.cors.enable=true
      - http.cors.allowed.origins=*
      - http.cors.allowed.headers=Origin,Accept,X-Requested-With,Content-Type,Access-Control-Allow-Origin,Access-Control-Request-Method,Access-Control-Request-Headers,Authorization
```
Error:
```
Failed to load http://test.dhcp:8081/FROST-Server/v1.0/Things: 
No 'Access-Control-Allow-Origin' header is present on the requested resource. 
Origin 'http://melissa.dhcp:8080' is therefore not allowed access.
```

**Comment by hylkevds** [comment]
Environment variables are not allowed to have the dot (.) character in the name. You must replace all of the dots in the names with an underscore (_).

**Comment by EOSIT** [comment]
My new docker-compose file looks like this:
```
      - serviceRootUrl=http://vostok.dhcp:8081/FROST-Server
      - http_cors_enable=true
      - http_cors_allowed_origins=*
      - http_cors_allowed_headers=Origin,Accept,X-Requested-With,Content-Type,Access-Control-Allow-Origin,Access-Control-Request-Method,Access-Control-Request-Headers,Authorization
```
But I get the same error.

Are other settings perhaps needed?

**Comment by EOSIT** [comment]
I am not sure what you mean; there is no output as such when starting the containers; but I can tru and start them in foreground mode and see what happens.

**Comment by EOSIT** [comment]
Here is the full output:
```
web_1       | 08-Oct-2018 13:44:27.291 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.5.32
web_1       | 08-Oct-2018 13:44:27.292 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Jun 20 2018 19:50:35 UTC
web_1       | 08-Oct-2018 13:44:27.293 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.5.32.0
web_1       | 08-Oct-2018 13:44:27.293 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
web_1       | 08-Oct-2018 13:44:27.293 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.10.0-38-generic
web_1       | 08-Oct-2018 13:44:27.293 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
web_1       | 08-Oct-2018 13:44:27.294 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-8-openjdk-amd64/jre
web_1       | 08-Oct-2018 13:44:27.294 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_171-8u171-b11-1~deb9u1-b11
web_1       | 08-Oct-2018 13:44:27.294 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
web_1       | 08-Oct-2018 13:44:27.294 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
web_1       | 08-Oct-2018 13:44:27.294 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
web_1       | 08-Oct-2018 13:44:27.294 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
web_1       | 08-Oct-2018 13:44:27.294 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
web_1       | 08-Oct-2018 13:44:27.295 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
web_1       | 08-Oct-2018 13:44:27.295 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
web_1       | 08-Oct-2018 13:44:27.295 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
web_1       | 08-Oct-2018 13:44:27.295 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
web_1       | 08-Oct-2018 13:44:27.295 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
web_1       | 08-Oct-2018 13:44:27.295 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
web_1       | 08-Oct-2018 13:44:27.295 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
web_1       | 08-Oct-2018 13:44:27.296 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded APR based Apache Tomcat Native library [1.2.17] using APR version [1.5.2].
web_1       | 08-Oct-2018 13:44:27.296 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
web_1       | 08-Oct-2018 13:44:27.296 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
web_1       | 08-Oct-2018 13:44:27.298 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.1.0f  25 May 2017]
web_1       | 08-Oct-2018 13:44:27.352 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
web_1       | 08-Oct-2018 13:44:27.360 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
web_1       | 08-Oct-2018 13:44:27.367 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
web_1       | 08-Oct-2018 13:44:27.368 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
web_1       | 08-Oct-2018 13:44:27.369 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 313 ms
web_1       | 08-Oct-2018 13:44:27.383 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
web_1       | 08-Oct-2018 13:44:27.383 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.32
web_1       | 08-Oct-2018 13:44:27.407 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/FROST-Server.war]
web_1       | 08-Oct-2018 13:44:28.884 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
web_1       | 13:44:28.991 [localhost-startStop-1] INFO   d.f.i.ilt.sta.ContextListener - Context initialised, loading settings.
web_1       | 13:44:29.007 [localhost-startStop-1] WARN   d.f.i.i.sta.settings.Settings - Could not read config value for bus.workerPoolSize, using default value 2.
web_1       | 13:44:29.008 [localhost-startStop-1] WARN   d.f.i.i.sta.settings.Settings - Could not read config value for bus.queueSize, using default value 100.
web_1       | 13:44:29.077 [localhost-startStop-1] WARN   d.f.i.i.sta.settings.Settings - Could not read config value for mqtt.persistent_store, using default value /usr/local/tomcat/work/Catalina/localhost/FROST-Server/moquette_store.mapdb.
web_1       | 13:44:29.078 [localhost-startStop-1] WARN   d.f.i.i.sta.settings.Settings - Could not read config value for mqtt.storage_class, using default value io.moquette.persistence.mapdb.MapDBPersistentStore.
web_1       | 13:44:29.078 [localhost-startStop-1] WARN   d.f.i.i.sta.settings.Settings - Could not read config value for mqtt.maxInFlight, using default value 50.
web_1       | 13:44:29.079 [localhost-startStop-1] INFO       io.moquette.server.Server - Configuring embedded Hazelcast instance
web_1       | 13:44:29.079 [localhost-startStop-1] INFO       io.moquette.server.Server - There are no Hazelcast intercept handlers. The server won't start a Hazelcast instance.
web_1       | 13:44:29.085 [localhost-startStop-1] INFO    i.m.p.m.MapDBPersistentStore - Initializing MapDB store
web_1       | 13:44:29.085 [localhost-startStop-1] INFO    i.m.p.m.MapDBPersistentStore - Using user-defined MapDB store file. Path=/usr/local/tomcat/work/Catalina/localhost/FROST-Server/moquette_store.mapdb
web_1       | 13:44:29.086 [localhost-startStop-1] WARN    i.m.p.m.MapDBPersistentStore - Using fresh MapDB store file. Path=/usr/local/tomcat/work/Catalina/localhost/FROST-Server/moquette_store.mapdb
web_1       | 13:44:29.352 [localhost-startStop-1] INFO    i.m.p.m.MapDBPersistentStore - Scheduling MapDB commit task
web_1       | 13:44:29.360 [localhost-startStop-1] INFO  i.m.p.mapdb.MapDBMessagesStore - Initialized store
web_1       | 13:44:29.385 [localhost-startStop-1] INFO       io.moquette.server.Server - Using default SSL context creator
web_1       | 13:44:29.389 [localhost-startStop-1] INFO  i.m.server.netty.NettyAcceptor - Netty is using NIO
web_1       | 13:44:29.618 [localhost-startStop-1] INFO  i.m.server.netty.NettyAcceptor - Server bound to host=0.0.0.0, port=1883, protocol=TCP MQTT
web_1       | 13:44:29.621 [localhost-startStop-1] INFO  i.m.server.netty.NettyAcceptor - Server bound to host=0.0.0.0, port=9876, protocol=Websocket MQTT
web_1       | 13:44:29.627 [localhost-startStop-1] INFO       io.moquette.server.Server - Moquette server has been started successfully in 549 ms
web_1       | 13:44:29.655 [localhost-startStop-1] INFO  d.f.i.i.s.m.m.MoquetteMqttServer - paho-client connecting to broker: tcp://localhost:1883
web_1       | 13:44:29.709 [nioEventLoopGroup-3-1] WARN   i.m.s.impl.SessionsRepository - Session does not exist. CId=SensorThings API Server (62e41c38-492f-4cad-b0bb-622fa6ae6b58)
web_1       | 13:44:29.713 [nioEventLoopGroup-3-1] WARN   i.m.s.impl.SessionsRepository - Session does not exist. CId=SensorThings API Server (62e41c38-492f-4cad-b0bb-622fa6ae6b58)
web_1       | 13:44:29.715 [localhost-startStop-1] INFO  d.f.i.i.s.m.m.MoquetteMqttServer - paho-client connected to broker
web_1       | 13:44:29.715 [localhost-startStop-1] INFO  d.f.i.i.s.m.m.MoquetteMqttServer - Checking for pre-existing subscriptions.
web_1       | 13:44:29.716 [localhost-startStop-1] INFO  d.f.i.i.s.m.m.MoquetteMqttServer - Found 0 pre-existing subscriptions.
web_1       | 08-Oct-2018 13:44:29.729 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/FROST-Server.war] has finished in [2,321] ms
web_1       | 08-Oct-2018 13:44:29.730 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/docs]
web_1       | 08-Oct-2018 13:44:29.769 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
web_1       | 08-Oct-2018 13:44:29.772 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/docs] has finished in [42] ms
web_1       | 08-Oct-2018 13:44:29.772 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/manager]
web_1       | 08-Oct-2018 13:44:29.818 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
web_1       | 08-Oct-2018 13:44:29.822 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/manager] has finished in [50] ms
web_1       | 08-Oct-2018 13:44:29.822 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/host-manager]
web_1       | 08-Oct-2018 13:44:29.863 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
web_1       | 08-Oct-2018 13:44:29.864 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/host-manager] has finished in [42] ms
web_1       | 08-Oct-2018 13:44:29.865 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/examples]
web_1       | 08-Oct-2018 13:44:30.007 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
web_1       | 08-Oct-2018 13:44:30.018 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/examples] has finished in [153] ms
web_1       | 08-Oct-2018 13:44:30.018 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/ROOT]
web_1       | 08-Oct-2018 13:44:30.054 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
web_1       | 08-Oct-2018 13:44:30.055 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/ROOT] has finished in [37] ms
web_1       | 08-Oct-2018 13:44:30.058 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
web_1       | 08-Oct-2018 13:44:30.069 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
web_1       | 08-Oct-2018 13:44:30.071 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 2701 ms
```

**Comment by hylkevds** [comment]
I think you've got an old docker image that does not have that feature yet.  Can you try upgrading your images and re-create the FROST container?

**Comment by EOSIT** [comment]
Thanks.

1. Is there a way to tell if I have the latest version?
2. How often should I be updating?  

I have now run:
```
docker-compose rm -f
docker-compose pull
docker-compose up --build -
```
However, when I now try to access some of the data that was displaying before the update, I now get a new error (and this happens in the browser) on some components e.g.:

```
http://test.dhcp:8081/FROST-Server/v1.0/Datastreams
```
returns:
```
Failed to execute query. See logs for details.
```
Why would this happen now when it was working before?  What log should I look at?

**Comment by hylkevds** [comment]
When to update: When https://github.com/FraunhoferIOSB/FROST-Server/blob/master/CHANGELOG.md contains a feature you want :)

Determine which version you run: That's tricky at the moment. I should look into automatically embedding the Git commit id into the source. In your case I noticed the output not listing all config settings, but only the missing ones. That changed in the last version, it now lists all config settings with their values.

Your new error: I suspect you need to update your database. Go to http://test.dhcp:8081/FROST-Server/, click "Database Status and Update", and click "Do Update" if there are any actual changes listed.

**Comment by EOSIT** [comment]
I already ran the "Do Update".  However, every time I refresh that page it shows exactly the same message so I am not sure the update is actually been run?
```
-- *********************************************************************
-- Update Database Script
-- *********************************************************************
-- Change Log: liquibase/tables.xml
-- Ran at: 10/9/18 6:59 AM
-- Against: sensorthings@jdbc:postgresql://database:5432/sensorthings
-- Liquibase version: 3.4.2
-- *********************************************************************

-- Lock Database
UPDATE public.databasechangeloglock SET LOCKED = TRUE, LOCKEDBY = '10327c3980d5 (172.18.0.3)', LOCKGRANTED = '2018-10-09 06:59:01.557' WHERE ID = 1 AND LOCKED = FALSE;

-- Release Database Lock
UPDATE public.databasechangeloglock SET LOCKED = FALSE, LOCKEDBY = NULL, LOCKGRANTED = NULL WHERE ID = 1;
```

**Comment by hylkevds** [comment]
Ok, then the database is not the problem :)
That message is what you get when everything is fine. Liquibase locks the changelog table, and releases the lock again.

Then you have to look into the logs of the web_1 container. That should contain an exception.

**Comment by EOSIT** [comment]
Which log?  None of the ones in `/usr/local/tomcat/logs` contain any error trace:
```
-rw-r----- 1 root root   9407 Oct  9 06:13 catalina.2018-10-09.log
-rw-r----- 1 root root      0 Oct  9 06:13 host-manager.2018-10-09.log
-rw-r----- 1 root root    459 Oct  9 06:13 localhost.2018-10-09.log
-rw-r----- 1 root root  10993 Oct  9 07:12 localhost_access_log.2018-10-09.txt
-rw-r----- 1 root root      0 Oct  9 06:13 manager.2018-10-09.log
```

**Comment by hylkevds** [comment]
It should be in the console output:
`docker logs web_1`

**Comment by hylkevds** [comment]
That's really odd. Your database seems to be missing PostGIS. 
How is the database tied into your setup? Are use using a docker container for database, or a separate one?

**Comment by EOSIT** [comment]
I am using a separate DB container, but server and database are built as part of the same compose file.  Bear in mind the system *was* working before running the update, and these errors did not happen.  Something has triggered this change.

**Comment by EOSIT** [comment]
Given that this is a test system and the data is created via a script process, one option is to clear the database of all data and start from the beginning. Then it may be possible to see if there is an error related to existing faulty data. 

Is there a simple way to clear the database of all data?

**Comment by hylkevds** [comment]
Yes, you can delete the volume in docker that stores the database data.
`docker volume ls` to see all used volumes

But that also makes it impossible to check what went wrong...
Are you using `mdillon/postgis:latest` ?
What is the output of `docker logs [your database container]`?

**Comment by hylkevds** [comment]
I strongly suspect you ran into this issue: https://github.com/appropriate/docker-postgis/issues/110

**Comment by EOSIT** [comment]
The database log shows the same error:
```
2018-10-09 07:21:29.615 UTC [39] ERROR:  could not access file "$libdir/postgis-2.4": No such file or directory
2018-10-09 07:21:29.615 UTC [39] STATEMENT:  select distinct "e1"."NAME", "e1"."PROPERTIES", "e1"."DESCRIPTION", "e1"."GEOM", "e1"."LOCATION", "e1"."ENCODING_TYPE", "e1"."ID"
	from "LOCATIONS" "e1"
	inner join "THINGS_LOCATIONS" "e2j1"
	on "e1"."ID" = "e2j1"."LOCATION_ID"
	inner join "THINGS" "e2"
	on "e2"."ID" = "e2j1"."THING_ID"
	where "e2"."ID" = $1
	limit $2
```
Yes, we are using `mdillon/postgis:latest`.

Re https://github.com/appropriate/docker-postgis/issues/110 - how is that `update-postgis.sh` script run?

**Comment by EOSIT** [comment]
Thanks. That works: output for reference:
```
root@6c4961b42fcf:/usr/local/bin# ./update-postgis.sh 
Updating PostGIS extensions 'template_postgis' to 2.5.0
NOTICE:  extension "postgis" already exists, skipping
NOTICE:  extension "postgis_topology" already exists, skipping
NOTICE:  extension "fuzzystrmatch" already exists, skipping
NOTICE:  extension "postgis_tiger_geocoder" already exists, skipping
ALTER EXTENSION
Updating PostGIS extensions 'sensorthings' to 2.5.0
NOTICE:  extension "postgis" already exists, skipping
NOTICE:  extension "postgis_topology" already exists, skipping
NOTICE:  extension "fuzzystrmatch" already exists, skipping
NOTICE:  extension "postgis_tiger_geocoder" already exists, skipping
ALTER EXTENSION
````

**Comment by EOSIT** [comment]
There are still issues. Nothing in the database log, but the log from the web  shows:
```
09:29:02.469 [http-nio-8080-exec-5] ERROR       c.q.sql.AbstractSQLQuery - Caught java.lang.IllegalStateException for select distinct "e1"."NAME", "e1"."PROPERTIES", "e1"."DESCRIPTION", "e1"."GEOM", "e1"."LOCATION", "e1"."ENCODING_TYPE", "e1"."ID"
from "LOCATIONS" "e1"
inner join "THINGS_LOCATIONS" "e2j1"
on "e1"."ID" = "e2j1"."LOCATION_ID"
inner join "THINGS" "e2"
on "e2"."ID" = "e2j1"."THING_ID"
where "e2"."ID" = ?
limit ?
09:29:02.470 [http-nio-8080-exec-5] ERROR  d.f.i.ilt.sta.service.Service - 
java.lang.IllegalStateException: Received resultset tuples, but no field structure for them
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2086)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:288)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:430)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:356)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:168)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:116)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:83)
	at org.apache.commons.dbcp2.DelegatingPreparedStatement.executeQuery(DelegatingPreparedStatement.java:83)
	at com.querydsl.sql.AbstractSQLQuery.iterateSingle(AbstractSQLQuery.java:370)
	at com.querydsl.sql.AbstractSQLQuery.iterate(AbstractSQLQuery.java:342)
	at de.fraunhofer.iosb.ilt.sta.persistence.postgres.longid.EntityCreator.visit(EntityCreator.java:199)
	at de.fraunhofer.iosb.ilt.sta.path.EntitySetPathElement.visit(EntitySetPathElement.java:58)
	at de.fraunhofer.iosb.ilt.sta.persistence.postgres.longid.PostgresPersistenceManagerLong.get(PostgresPersistenceManagerLong.java:473)
	at de.fraunhofer.iosb.ilt.sta.service.Service.executeGet(Service.java:234)
	at de.fraunhofer.iosb.ilt.sta.service.Service.execute(Service.java:94)
	at de.fraunhofer.iosb.ilt.sta.Servlet_1_0.executeService(Servlet_1_0.java:135)
	at de.fraunhofer.iosb.ilt.sta.Servlet_1_0.processGetRequest(Servlet_1_0.java:72)
	at de.fraunhofer.iosb.ilt.sta.Servlet_1_0.doGet(Servlet_1_0.java:190)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	at de.fraunhofer.iosb.ilt.sta.Servlet_1_0.service(Servlet_1_0.java:228)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.filters.CorsFilter.handleNonCORS(CorsFilter.java:364)
	at org.apache.catalina.filters.CorsFilter.doFilter(CorsFilter.java:170)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:800)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:806)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by hylkevds** [comment]
I've reproduced the earlier error, and after running the update, the error is gone. I'm not seeing this later error.
From some web-searching for the error it seems it might go away after restarting the application and/or the database. Can you give that a try?

**Comment by EOSIT** [comment]
Yes, thanks, that works now!

Do you think that if we do upgrades in future we will need to rerun the `update-postgis.sh` script?
